name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:

jobs:
  test:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: idempotency_plug_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        version:
          - elixir: 1.15
            otp: 26.0
    runs-on: ubuntu-latest
    name: OTP ${{matrix.version.otp}} / Elixir ${{matrix.version.elixir}}
    env:
      MIX_ENV: test
      POSTGRES_URL: ecto://postgres:postgres@localhost/idempotency_plug_test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.version.otp}}
          elixir-version: ${{matrix.version.elixir}}
      - run: mix deps.get mix compile --warnings-as-errors
      - run: mix test
      - run: mix credo

